### PR TITLE
Enhancements in Repo-to-PDF: TypeScript Transition & New PDF Options

### PR DESCRIPTION
**Pull request by malpou**
Hello @BankkRoll,

This pull request incorporates a significant number of changes and improvements to the Repo-to-PDF package. Our primary aim is to make the package more flexible and user-friendly. 

**Key changes include:**

1. Transition from JavaScript to TypeScript: To enhance code quality and dev ex, we've converted the existing JavaScript codebase to TypeScript.

2. More Options for PDF Generation: We have added several options for the PDF generation process, providing users with increased customization. Now, users can:
- [x] Include or exclude line numbers in the PDF.
- [x] Choose whether to include code highlighting in the PDF.
- [x] Decide whether to remove comments from the code.
- [x] Opt to remove empty lines from the code.
- [x] Decide between a single large PDF file or individual PDFs per file in the repo.
- [x] When choosing a single large file users can decide to add page numbers.

   
3. Customizable Ignore Settings: Users can now create a `repo2pdf.ignore` file in their repository root to specify file types and directories to ignore during the PDF generation.

4. README Update: We've updated the README to reflect these changes, including new usage instructions.

As a result of these major changes and improvements, we have proposed to update the version from 1.2.1 to 2.0.0.

We believe that these changes will greatly enhance the Repo-to-PDF package and its utility for users. We hope you'll consider merging these improvements into the main project and publishing a new version on NPM.

Best Regards,
@malpou & @LucasionGS

### CODE REVIEW

**Comment by malpou** [comment]
While the bulk of the improvements have been completed and are ready for review, we are still in the process of refining a couple of features:

1. **Table of Contents:** We are actively working on the 'table of contents' feature. We want to ensure that it accurately reflects the repository's structure and provides a helpful navigation aid for larger PDFs. 

2. **Page Numbers:** We've encountered a specific issue with the page numbering where the first-page number is being appended to a new page at the end of the PDF. This is clearly not intended behavior, and we are currently debugging to resolve this issue to ensure that page numbers consistently appear in their correct locations.

We aim to have these updates completed soon. We'll push our changes and provide a status update once they are ready.

**Comment by BankkRoll** [comment]
Wow! I apologize for the delay in responding to your message. It has come to my attention rather late in the evening, and I shall make it a priority to thoroughly review and address the requests you have made tomorrow. Your dedication and expertise has surpassed my expectations, and I am truly impressed by the progress you all have achieved thus far. I've never had contributions to my projects to this extent, so I'm blown away! The project, originally started as a small AI conversion task. I extend my sincerest gratitude to both @malpou and @LucasionGS for your exceptional work. Again,  I apologize for the delay. I will provide further updates and insights on the matter when I revisit this tomorrow.

**Comment by malpou** [comment]
On vacation at the moment, i'll take a look at the last things sometime next week.

**Comment by BankkRoll** [comment]
Hey no rush at all, just checking to see if there was any updates on this PR @malpou ? Just getting some new forks and downloads and would love to have your updated version. Thanks!

**Comment by malpou** [comment]
Have had some work to take care of, i'll clean up a branch with What is working right now.

And then we'll fix the last few things when time allows it.

**Comment by malpou** [comment]
Hi @BankkRoll , it should be ready now. 

I skipped the table of contents for now since it was still causing some issues.

Best regards
Malthe

**Comment by BankkRoll** [comment]
Hey @malpou, 

I've done testing on the proposed changes with a variety of repositories and the results have been consistently excellent. However, when applying the changes to certain specific repositories, notably the freeCodeCamp repository, I've encountered a couple of distinct errors.

1. The error message `Could not find the language '', did you forget to load/include a language module?` occurred. The fix for this should involve verifying the language before attempting to apply highlighting.
2. A `Fatal JavaScript invalid size error` was also triggered.

These changes you have made will be merged into V2.0.0, and I will implement a patch (2.0.1) to address the first issue. The fatal error might be indicative of a need for further code optimization or could point towards a memory leak.

I would like to express my appreciation for both of your valuable contributions once again!

**Comment by malpou** [comment]
Thanks for the merge.

When the time comes around, I'll make a PR for the table of contents.

Have a good one until then 😄

**Pull request merged**
